#release configuration
#Fri Dec 04 11:18:05 MST 2020
projectVersionPolicyId=default
remoteTagging=true
scm.commentPrefix=[maven-release-plugin] 
project.rel.springexample\:pet-clinic-web=0.0.1
project.scm.springexample\:pet-clinic.tag=HEAD
project.scm.springexample\:pet-clinic-data.empty=true
completedPhase=generate-release-poms
project.scm.springexample\:pet-clinic.developerConnection=scm\:git\:https\://github.com/slittleton/pet-clinic.git
scm.url=scm\:git\:https\://github.com/slittleton/pet-clinic.git
project.scm.springexample\:pet-clinic-web.empty=true
project.dev.springexample\:pet-clinic-data=0.0.2-SNAPSHOT
scm.tagNameFormat=@{project.artifactId}-@{project.version}
project.rel.springexample\:pet-clinic=0.0.1
pushChanges=true
project.dev.springexample\:pet-clinic-web=0.0.2-SNAPSHOT
project.rel.springexample\:pet-clinic-data=0.0.1
scm.tag=0.0.1
project.dev.springexample\:pet-clinic=0.0.2-SNAPSHOT
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
