#release configuration
#Fri Dec 04 11:16:40 MST 2020
projectVersionPolicyId=default
scm.tagNameFormat=@{project.artifactId}-@{project.version}
remoteTagging=true
scm.commentPrefix=[maven-release-plugin] 
pushChanges=true
completedPhase=check-poms
scm.url=scm\:git\:https\://github.com/slittleton/pet-clinic.git
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
